*/ Retrieve

SELECT * FROM nasabah;
SELECT * FROM akun;
SELECT * FROM transaksi;

*/ Update

UPDATE [NAMA TABEL] 
SET [KOLOM] 
WHERE [KONDISI]

*/ Delete

DELETE FROM NAMA TABEL WHERE KONDISI;

*/Cretae
INSERT INTO NAMA TABEL (KOLOM1, KOLOM2, KOLOM3, ...)
VALUES (VALUE1, VALUE2, VALUE3, ...);